### ISSUE TITLE
Does it work with Rails < 5.2.3 ?

### ISSUE THREAD

**Issue by henvo** [linqueta/rails-healthcheck#18]
Hey,

I wanted to use this gem since it seems pretty clean and like a good alternative to the `health_check` gem.

Unfortunately I wasn't able to install it due to the rather strict requirements of the Rails gem:

```
    rails-healthcheck (>= 1.0.6) was resolved to 1.0.6, which depends on
      rails (>= 5.2.3)
```

Would it be possible to allow Rails versions prior to 5.2.3? Or what are the reasons that it should only be used with Rails >= 5.2.3 ?

Best

**Comment by linqueta** [comment]
Hey bro, 

I've tested in other versions and removed the version rule and deployed another version. Please run `bundle update` in your project and use it.

If you have some problem just tell here.

**Comment by linqueta** [comment]
#19
