### ISSUE TITLE
Is it possible to configure success and/or error codes to return string instead?

### ISSUE THREAD

**Issue by puneetpandey** [linqueta/rails-healthcheck#24]
Hi,

I came across this gem and found this very useful (w.r.t. other less maintained gems and it's simplicity of usage) and curious to know, if I can configure the `success` and/or `error` such that it returns a string (for e.g. `config.success = 'success'`, so when I hit http://localhost:3000/healthcheck, I should see success as plain text OR I can pass a template URL?

I am trying that but not working.

It would be nice to have add-ons, if we add below to supported list:

1. `config.success = 'success'`
2. `config.success = '/path/to/template/file'`
OR
3. Add a block for success and/or error codes: `config.success do; do_something_here; end`

**Comment by linqueta** [comment]
Hey @puneetpandey ,

I understood your question but I'm not sure if it is necessary for what this gem proposes to resolve. But, if you want you can code it and open a pull request here for me understood as well.

Best!

**Comment by linqueta** [comment]
Hey @puneetpandey 

I've pushed a feature for custom responses, maybe it may solve your problem using this gem.
