### ISSUE TITLE
Can't run rails generate healthcheck:install in docker

### ISSUE THREAD

**Issue by LeoFragozo** [linqueta/rails-healthcheck#27]
I'm trying to run the rake in docker but got this log

Running via Spring preloader in process 29
Traceback (most recent call last):
	33: from -e:1:in `<main>'
	32: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	31: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	30: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
	29: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	28: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
	27: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	26: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	25: from /app_colab_enjoei/bin/rails:9:in `<top (required)>'
	24: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
	23: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
	22: from /usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
	21: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	20: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	19: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	18: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	17: from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	16: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
	15: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command.rb:46:in `invoke'
	14: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/command/base.rb:69:in `perform'
	13: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	12: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	10: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	 9: from /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/generators.rb:276:in `invoke'
	 8: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	 7: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	 6: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	 5: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	 4: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	 3: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	 2: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	 1: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/rails-healthcheck-1.1.2/lib/generators/healthcheck/install_generator.rb:8:in `create_initializer_file': undefined method `desc' for #<Healthcheck::InstallGenerator:0x0000557606742d28> (NoMethodError)

already ran docker-compose up --build, and docker-compose run web bundle install but the error keep going up.

**Comment by linqueta** [comment]
Hey bro,

It was really with a problem, but I've fixed it in #28 . Thank you!

**Comment by LeoFragozo** [comment]
flawless!
