### ISSUE TITLE
Version check - concept

### ISSUE THREAD

**Issue by marcinwierzbicki** [linqueta/rails-healthcheck#40]
# Concept draft:

## Endpoint
`GET /healthcheck?required_version=:version` when `version` is eg.`>=  6.0.3` (Gemfile style)

## Source of version
 -  method implemented in initializer (default: `ENV['APP_VERSION']`)

## Use case
As an administrator - not having full control over all microservices - I would like to be able to check if the entire stack is in the correct versions.

What do you think about this feature?

**Comment by linqueta** [comment]
Hey @marcinwierzbicki 

I really appreciate that, and, if you want, you may send a pull request with this feature.
