### ISSUE TITLE
Verbose mode with successful response

### ISSUE THREAD

**Issue by nicolas-brousse** [linqueta/rails-healthcheck#52]
Hi,

I previously used [`server_health_check-rails`](https://github.com/on-site/server_health_check-rails) and looking to switching to a new one. I saw this gem and like the approach.

There is two things I would like to see ; token in URL (I've open a PR), and a verbose mode in successful response.

Do you think it is possible to make response always return json content if verbose enabled? Like following:
```json
{
  "status": {
    "heartbeat": "OK",
    "active_record": "OK",
    "sidekiq": "OK",
    "cache": "OK",
    "database": "OK",
    "migrations": "OK",
    "activestorage": "OK",
    "email": "OK"
  }
}
```

**Comment by linqueta** [comment]
Yeah man, of course we can add it.

So, as I said in your PR, I only need to refactor that controller, but at this week we can deploy it.

**Comment by nicolas-brousse** [comment]
@linqueta thanks for your feedback. No pressure.

**Comment by linqueta** [comment]
Hey, sorry about late, but can you check the pr #56 solves this issue problem?

**Comment by linqueta** [comment]
I deployed and push a new version of the gem with your suggestion.

**Comment by nicolas-brousse** [comment]
Hey @linqueta, Thanks for the change. I'll have a look on it this week. But changes seems to look pretty :+1:

**Comment by nicolas-brousse** [comment]
Hey @linqueta I just check and looks good. Thanks again
