### ISSUE TITLE
Check if ActiveJob is working?

### ISSUE THREAD

**Issue by epugh** [linqueta/rails-healthcheck#62]
I am using Redis for ActiveJob, and it would be good to know if it was up and running.  How would I add that?

**Comment by linqueta** [comment]
Are you using Sidekiq (Redis) for ActiveJobs?  If it is truth, you can use something like:

```ruby
  config.add_check :sidekiq,  -> { raise StandardError, 'Sidekiq is down' if Sidekiq::ProcessSet.new.size.zero? }
``` 

[Sidekiq guide](https://github.com/mperham/sidekiq/wiki/API#processes)

But, if you want just to check redis, you can use: 

```ruby
  config.add_check :redis,  -> { Redis.new(connection_params).ping }
``` 

[Redis guide](https://github.com/redis/redis-rb#error-handling)

**Comment by epugh** [comment]
BTw, I am finally taking advantage of this!   Looked at the Rails healthcheck, and it seems too limited for me..
